import { Hero } from "../interfaces/hero.interface";

export const heroSorshiSamurai: Hero = {
  id: 'hero_sorshi_001',
  name: 'Sorshi',
  description: 'Son of Tokugawa',
  normal: {
    baseStats: { hp: 900, defense: 70, speed: 90, evasion: 0.06 },
    ability: {
      name: 'Quick Slash',
      description: 'Fast attack on single enemy',
      attack: 250,
      heal: 0,
      critChance: 0.07,
      critPower: 1.3,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
    basicAttack: {
      name: "Katana Strike",
      description: "Basic sword attack",
      attack: 80,
      heal: 0,
      critChance: 0.05,
      critPower: 1.4,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  rare: {
    baseStats: { hp: 1000, defense: 80, speed: 95, evasion: 0.07 },
    ability: {
      name: 'Iaijutsu',
      description: 'Instant strong strike',
      attack: 320,
      heal: 0,
      critChance: 0.1,
      critPower: 1.5,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
    basicAttack: {
      name: "Katana Strike",
      description: "Basic sword attack",
      attack: 95,
      heal: 0,
      critChance: 0.07,
      critPower: 1.7,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  epic: {
    baseStats: { hp: 1100, defense: 95, speed: 100, evasion: 0.08 },
    ability: {
      name: 'Dragon Dance',
      description: 'AoE sword dance attack',
      attack: 450,
      heal: 0,
      critChance: 0.12,
      critPower: 1.8,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'AoE',
    },
    basicAttack: {
      name: "Katana Strike",
      description: "Basic sword attack",
      attack: 110,
      heal: 0,
      critChance: 0.1,
      critPower: 2,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  legendary: {
    baseStats: { hp: 1300, defense: 110, speed: 110, evasion: 0.09 },
    ability: {
      name: 'Samurai’s Wrath',
      description: 'Massive AoE slash attack',
      attack: 600,
      heal: 0,
      critChance: 0.15,
      critPower: 2.2,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'AoE',
    },
    basicAttack: {
      name: "Katana Strike",
      description: "Basic sword attack",
      attack: 130,
      heal: 0,
      critChance: 0.15,
      critPower: 2.4,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
};
