import { Hero } from "../interfaces/hero.interface";

export const heroEuphoriaDemon: Hero = {
  id: 'hero_euphoria_001',
  name: 'Euphoria',
  description: 'Half-Demon born in heaven',
  normal: {
    baseStats: { hp: 900, defense: 70, speed: 80, evasion: 0.04 },
    ability: {
      name: 'Demonic Slash',
      description: 'Deals damage and causes fear',
      attack: 350,
      heal: 0,
      critChance: 0.06,
      critPower: 1.3,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
    basicAttack: {
      name: "Claw Swipe",
      description: "Basic claw attack",
      attack: 80,
      heal: 0,
      critChance: 0.05,
      critPower: 1.4,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  rare: {
    baseStats: { hp: 1050, defense: 85, speed: 85, evasion: 0.05 },
    ability: {
      name: 'Hellfire Burst',
      description: 'AoE fire damage and burn',
      attack: 420,
      heal: 0,
      critChance: 0.1,
      critPower: 1.6,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'AoE',
    },
    basicAttack: {
      name: "Claw Swipe",
      description: "Basic claw attack",
      attack: 95,
      heal: 0,
      critChance: 0.07,
      critPower: 1.6,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  epic: {
    baseStats: { hp: 1200, defense: 100, speed: 90, evasion: 0.06 },
    ability: {
      name: 'Demon’s Wrath',
      description: 'Massive AoE damage and fear',
      attack: 600,
      heal: 0,
      critChance: 0.15,
      critPower: 2,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'AoE',
    },
    basicAttack: {
      name: "Claw Swipe",
      description: "Basic claw attack",
      attack: 115,
      heal: 0,
      critChance: 0.1,
      critPower: 2.2,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  legendary: {
    baseStats: { hp: 1400, defense: 120, speed: 100, evasion: 0.07 },
    ability: {
      name: 'Infernal Rampage',
      description: 'Devastating AoE demon attack',
      attack: 850,
      heal: 0,
      critChance: 0.2,
      critPower: 2.6,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'AoE',
    },
    basicAttack: {
      name: "Claw Swipe",
      description: "Basic claw attack",
      attack: 140,
      heal: 0,
      critChance: 0.15,
      critPower: 2.8,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
};
