import { Hero } from "../interfaces/hero.interface";

export const heroJacobKnight: Hero = {
  id: 'hero_jacob_001',
  name: 'Jacob',
  description: 'Knight of Sun',
  normal: {
    baseStats: { hp: 1100, defense: 120, speed: 50, evasion: 0.02 },
    ability: {
      name: 'Solar Shield',
      description: 'Raises defense of all allies for 3 turns',
      attack: 0,
      heal: 0,
      critChance: 0,
      critPower: 1,
      defense: 30,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'team',
    },
    basicAttack: {
      name: "Shield Bash",
      description: "Stuns the enemy briefly",
      attack: 70,
      heal: 0,
      critChance: 0.05,
      critPower: 1.3,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  rare: {
    baseStats: { hp: 1300, defense: 140, speed: 55, evasion: 0.03 },
    ability: {
      name: 'Radiant Guard',
      description: 'Creates a shield that absorbs damage for all allies for 3 turns',
      attack: 0,
      heal: 0,
      critChance: 0,
      critPower: 1,
      defense: 40,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'team',
    },
    basicAttack: {
      name: "Shield Bash",
      description: "Stuns the enemy briefly",
      attack: 90,
      heal: 0,
      critChance: 0.07,
      critPower: 1.5,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  epic: {
    baseStats: { hp: 1500, defense: 170, speed: 60, evasion: 0.04 },
    ability: {
      name: 'Sunlight Barrier',
      description: 'Grants a damage shield and heals allies for 3 turns',
      attack: 0,
      heal: 150,
      critChance: 0,
      critPower: 1,
      defense: 50,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'team',
    },
    basicAttack: {
      name: "Shield Bash",
      description: "Stuns the enemy briefly",
      attack: 110,
      heal: 0,
      critChance: 0.1,
      critPower: 1.7,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  legendary: {
    baseStats: { hp: 1800, defense: 210, speed: 65, evasion: 0.05 },
    ability: {
      name: 'Solar Wrath',
      description: 'Deals massive AoE damage and stuns enemies',
      attack: 300,
      heal: 0,
      critChance: 0.15,
      critPower: 2,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'AoE',
    },
    basicAttack: {
      name: "Shield Bash",
      description: "Stuns the enemy briefly",
      attack: 130,
      heal: 0,
      critChance: 0.15,
      critPower: 2,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
};
