import { Hero } from "../interfaces/hero.interface";

export const heroAstoriaPrincess: Hero = {
  id: 'hero_astoria_001',
  name: 'Astoria',
  description: 'Princess of Stars',
  normal: {
    baseStats: { hp: 800, defense: 60, speed: 70, evasion: 0.04 },
    ability: {
      name: 'Healing Light',
      description: 'Heals a single ally',
      attack: 0,
      heal: 150,
      critChance: 0,
      critPower: 1,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
    basicAttack: {
      name: "Star Shot",
      description: "Basic magical attack",
      attack: 65,
      heal: 0,
      critChance: 0.05,
      critPower: 1.3,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  rare: {
    baseStats: { hp: 900, defense: 70, speed: 75, evasion: 0.05 },
    ability: {
      name: 'Radiant Heal',
      description: 'Heals all allies over time (3 turns)',
      attack: 0,
      heal: 60,
      critChance: 0,
      critPower: 1,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'team',
    },
    basicAttack: {
      name: "Star Shot",
      description: "Basic magical attack",
      attack: 80,
      heal: 0,
      critChance: 0.07,
      critPower: 1.5,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  epic: {
    baseStats: { hp: 1000, defense: 85, speed: 80, evasion: 0.06 },
    ability: {
      name: 'Starlight Blessing',
      description: 'Strong heal and defense buff to all allies for 3 turns',
      attack: 0,
      heal: 150,
      critChance: 0,
      critPower: 1,
      defense: 30,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'team',
    },
    basicAttack: {
      name: "Star Shot",
      description: "Basic magical attack",
      attack: 100,
      heal: 0,
      critChance: 0.1,
      critPower: 1.8,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  legendary: {
    baseStats: { hp: 1200, defense: 100, speed: 85, evasion: 0.07 },
    ability: {
      name: 'Celestial Light',
      description: 'Massive heal and cleanse all allies',
      attack: 0,
      heal: 300,
      critChance: 0,
      critPower: 1,
      defense: 50,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'team',
    },
    basicAttack: {
      name: "Star Shot",
      description: "Basic magical attack",
      attack: 120,
      heal: 0,
      critChance: 0.15,
      critPower: 2,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
};
