import { Hero } from "../interfaces/hero.interface";

export const heroLamb: Hero = {
  id: 'hero_lamb_001',
  name: 'Lamb',
  description: 'the Chosen',
  normal: {
    baseStats: { hp: 850, defense: 60, speed: 75, evasion: 0.05 },
    ability: {
      name: 'Sacred Flame',
      description: 'Burns enemies with holy fire',
      attack: 300,
      heal: 0,
      critChance: 0.05,
      critPower: 1.3,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'AoE',
    },
    basicAttack: {
      name: "Holy Swipe",
      description: "Basic holy attack",
      attack: 70,
      heal: 0,
      critChance: 0.05,
      critPower: 1.4,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  rare: {
    baseStats: { hp: 950, defense: 70, speed: 80, evasion: 0.06 },
    ability: {
      name: 'Purifying Light',
      description: 'Heals allies and burns undead',
      attack: 0,
      heal: 30,
      critChance: 0,
      critPower: 1,
      defense: 20,
      speed: 0,
      evation: 0,
      duration: 3,
      target: 'team',
    },
    basicAttack: {
      name: "Holy Swipe",
      description: "Basic holy attack",
      attack: 85,
      heal: 0,
      critChance: 0.07,
      critPower: 1.6,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  epic: {
    baseStats: { hp: 1100, defense: 90, speed: 85, evasion: 0.07 },
    ability: {
      name: 'Divine Wrath',
      description: 'Deals holy damage to all enemies',
      attack: 450,
      heal: 0,
      critChance: 0,
      critPower: 1.9,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'AoE',
    },
    basicAttack: {
      name: "Holy Swipe",
      description: "Basic holy attack",
      attack: 105,
      heal: 0,
      critChance: 0.1,
      critPower: 2.1,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  legendary: {
    baseStats: { hp: 1300, defense: 110, speed: 95, evasion: 0.08 },
    ability: {
      name: 'Judgement Day',
      description: 'Massive holy AoE damage',
      attack: 650,
      heal: 0,
      critChance: 0.15,
      critPower: 2.4,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'AoE',
    },
    basicAttack: {
      name: "Holy Swipe",
      description: "Basic holy attack",
      attack: 130,
      heal: 0,
      critChance: 0.15,
      critPower: 2.6,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
};
