import { Hero } from "../interfaces/hero.interface";

export const heroEmilianMage: Hero = {
  id: 'hero_emilian_001',
  name: 'Emilian',
  description: 'Mysteriuos dark mage',
  normal: {
    baseStats: { hp: 700, defense: 50, speed: 90, evasion: 0.05 },
    ability: {
      name: 'Shadow Bolt',
      description: 'Shoots a bolt of dark energy',
      attack: 300,
      heal: 0,
      critChance: 0.05,
      critPower: 1.2,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
    basicAttack: {
      name: "Dark Tap",
      description: "A weak magical hit",
      attack: 60,
      heal: 0,
      critChance: 0.05,
      critPower: 1.5,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  rare: {
    baseStats: { hp: 750, defense: 60, speed: 95, evasion: 0.06 },
    ability: {
      name: 'Dark Surge',
      description: 'Area damage of shadow flames',
      attack: 350,
      heal: 0,
      critChance: 0.08,
      critPower: 1.4,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'AoE',
    },
    basicAttack: {
      name: "Dark Tap",
      description: "A weak magical hit",
      attack: 75,
      heal: 0,
      critChance: 0.07,
      critPower: 1.7,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  epic: {
    baseStats: { hp: 800, defense: 70, speed: 100, evasion: 0.07 },
    ability: {
      name: 'Void Eruption',
      description: 'Massive dark explosion damaging all enemies',
      attack: 500,
      heal: 0,
      critChance: 0.12,
      critPower: 1.8,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'AoE',
    },
    basicAttack: {
      name: "Dark Tap",
      description: "A weak magical hit",
      attack: 90,
      heal: 0,
      critChance: 0.1,
      critPower: 2,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
  legendary: {
    baseStats: { hp: 850, defense: 80, speed: 110, evasion: 0.08 },
    ability: {
      name: 'Nightmare Blast',
      description: 'Unleashes a devastating shadow storm',
      attack: 700,
      heal: 0,
      critChance: 0.2,
      critPower: 2.5,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'AoE',
    },
    basicAttack: {
      name: "Dark Tap",
      description: "A weak magical hit",
      attack: 110,
      heal: 0,
      critChance: 0.15,
      critPower: 2.7,
      defense: 0,
      speed: 0,
      evation: 0,
      duration: 0,
      target: 'single',
    },
  },
};
